overview:
  - name: First Item
    description: First Item Description
    levels: ["a"]
  - name: Second Item
    description: Second Item Description
    levels: ["b"]
observability:
  - name: Third Item
    description: Third Item Description
    levels: ["c"]
